# Generated by Django 4.2.1 on 2023-06-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='deal',
            options={'verbose_name': 'Сделка', 'verbose_name_plural': 'Сделки'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'Владелец', 'verbose_name_plural': 'Владельцы'},
        ),
        migrations.AlterModelOptions(
            name='propertytype',
            options={'verbose_name': 'Тип недвижимости', 'verbose_name_plural': 'Типы недвижимости'},
        ),
        migrations.AlterModelOptions(
            name='realestate',
            options={'ordering': ['title', 'price'], 'verbose_name': 'Недвижимость', 'verbose_name_plural': 'Недвижимость'},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'verbose_name': 'Вид услуги', 'verbose_name_plural': 'Виды услуг'},
        ),
        migrations.AlterField(
            model_name='deal',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
